name: release
run-name: Build and Publish-to-Nuget

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build library (.net core)
        run: dotnet build src/HJ212Interpreter/HJ212Interpreter.csproj --configuration release

  publish:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Version
        id: getversion
        shell: pwsh
        run: |
          $xml = [xml](Get-Content ./src/HJ212Interpreter/HJ212Interpreter.csproj)
          $version = $xml.Project.PropertyGroup[1].Version
          echo "::set-output name=version::$version"
      - name: Publish package
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Publish NuGet
        run: |
          dotnet build src/HJ212Interpreter/HJ212Interpreter.csproj --configuration release
          nuget push src/HJ212Interpreter/bin/release/HJ212Interpreter.${{ steps.getversion.outputs.version }}.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
